### ISSUE TITLE
CSS looks good

### ISSUE THREAD

**Issue by SidTheEngineer** [sun0019/assignment1#2]
I don't see any major issues with the CSS. Syntax/formatting/indentation all look good and the code is clean/concise. One small suggestion I have would be moving your "brushes", "frames", and "finish" classes to the `<h3>` elements so we can style them directly without having to include "h3" in our selector, like so:

```CSS
.brushes {
  background-color: mediumspringgreen;
}
```
